### ISSUE TITLE
Doesn't read F keys

### ISSUE THREAD

**Issue by k1epto** [terrabitz/QuackTest#1]
I'm sure you probably won't update just to fix this, but it doesn't read F keys ... All I wanted was for it to F11 my browser screen... NOPE. ugh... Great app btw, thanks for making it!!! Also if you do make changes again on it, maybe add an encoder to it as well... I'm surprised you didn't to begin with.

**Comment by terrabitz** [comment]
Hey @bipolarmorgan, I just opened up a separate issue in #2  for the encoding feature. Not sure if I'll get to it, but it's there. :) I'll take a look and see if I can't get to an update for the function key issue sometime this week.

**Comment by k1epto** [comment]
Kool,  thanks! I love the app! Very useful for testing.

**Comment by terrabitz** [comment]
@bipolarmorgan v0.2.0 has been release, which should contain the ability to interpret function keys. I haven't done extensive testing with function key combos, but basic ones (like F11 to make a window fullscreen) do work.

**Comment by k1epto** [comment]
Tested on Windows 7 32bit, it says incompatible with this version of windows. Did you only compile it in 64 bit or something? the previous version loaded just fine on this system.

**Comment by k1epto** [comment]
Tested on Windows 10 64bit, working as expected. Thanks for the update. @terrabitz  can you make it 32bit compatible?

**Comment by terrabitz** [comment]
@bipolarmorgan I have created another issue (#5) to address multiple-architecture support. I'm going to go ahead and close this issue.
